import MarkdownRender from "@/components/theme/Markdowns";
import { useRouter } from "next/router";
import { ReactMarkdown } from "react-markdown/lib/react-markdown";
import remarkGfm from "remark-gfm";

const content = `
# Privacy Policy for Review Express
This Privacy Policy describes how Review Express (the Extension) collects, uses, and discloses your information when you use our services. We value your privacy and are committed to protecting it.

## 1. Data We Collect
The Extension collects and processes the following data:

- **Web Page Content**: Upon your activation, we collect most of the content of the web page you're browsing along with the text you highlighted in that web page to provide you with the Extension's summarizing functionalities.
- **User Queries**: When you select a summary mode or ask a question, your query is sent to our server.


## 2. How Your Data is Used
We use the data collected for the following purposes:

- **To Provide Services**: The Extension uses the collected web page content and your queries to summarize the web page content based on the selected summary mode or to answer your queries.  
- **To Improve Our Services**: We may use your usage data to understand how our users use our Extension and to improve our services (e.g. for debugging and estimation of the running cost). The web page content you submit and the summary generated will never be analysed or read by a human without your explicit permissions. 


## 3. Data Retention
The extension retains the aformentioned data for as long as you maintain an account with us. This includes the content of the web pages you've summarized, your queries, and the corresponding summaries and answers generated by the Extension.

This data is kept to provide you with a history of your past summaries and answers, enhancing your user experience by allowing you to revisit your past interactions with our service. 

You can delete the data associated with each article directly through the user interface in the Extension. Once deleted, the data is permanently removed from our servers and cannot be recovered. 

If you wish to delete your account and all the data associated with it, you will need to contact us directly. Upon receiving such a request, we will promptly delete your data from our servers.


## 4. Data Sharing
- **OpenAI**: Your queries and the associated web page content will be sent to OpenAI to generate the summary of the web page content. It is upto OpenAI to decide how your data is used and it is beyond our control. Please refer to OpenAI's [privacy policy](https://openai.com/policies/) and [API data usage policy](https://openai.com/policies/api-data-usage-policies) for more information. Do not use this extension if you have concerns about OpenAI's privacy policy.


Unless legally required, your data is not shared with third parties for any purposes other than those described in this policy. 


## 5. User Consent
By using our Extension, you consent to the collection and use of your information as described in this policy. The Extension will not collect your data unless you activate it (by pressing the keyboard shortcut or clicking on the context menu), thus giving your consent.
`;

const H1 = ({...props }) => (
  <h1 className="text-2xl font-bold mt-9 mb-3 mx-5" {...props} />
);
const H2 = ({...props }) => (
  <h2 className="text-xl font-bold mt-9 mb-3  mx-5" {...props}/>
);
const Link= ( {...props} ) => (
  <a className="text-blue-500 hover:underline"  {...props}/>
);
const P= ( {...props} ) => (
  <p className="my-3 mx-5" {...props} />
);

const UL = ({ ...props }) => (
  <ul className="list-disc list-outside my-3 mx-10" {...props} />
)

const LI = ({ ...props }) => (
  <li className="my-3 " {...props} />
)


export default function PrivacyPolicy({}) {
  return (
    <MarkdownRender>{content}</MarkdownRender>
  );
}
